export interface PalmistryItem {
  id: string;
  name: string;
  category: 'lines' | 'mounts' | 'fingers' | 'markings';
  planet?: string;
  planetSymbol?: string;
  constellationPoints?: [number, number][]; // Line segments for planet constellation
  rating: number; // 1-5 rating
  meaning: string;
  traits: string[];
  positiveIndications: string[];
  challengingIndications: string[];
  modernPsychology: string;
  compatibleCareers: string[];
  relationships: string;
  health: string;
  famousPeople: string[];
  // SVG rendering path
  path: string;
  labelX: number;
  labelY: number;
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export const palmistryItems: PalmistryItem[] = [
  // --- LINES ---
  {
    id: 'life-line',
    name: 'Life Line',
    category: 'lines',
    rating: 5,
    meaning: 'Vitality, life force, physical strength, and major life path changes.',
    traits: ['Resilience', 'Physical Energy', 'Adaptability', 'Zest for life'],
    positiveIndications: ['Deep, clear line: robust health, high vitality', 'Long, sweeping line: stable, balanced lifestyle'],
    challengingIndications: ['Breaks in the line: major life transitions or disruptions', 'Chained pattern: delicate health or high nervous energy'],
    modernPsychology: 'Represents your physiological grounding, stress tolerance, and foundational sense of safety.',
    compatibleCareers: ['Healthcare', 'Athletics', 'Adventure tourism', 'Physical therapy'],
    relationships: 'Indicates the energetic reservoir available for long-term commitments and emotional bonding.',
    health: 'Relates to the nervous system, core vitality, and physical stamina.',
    famousPeople: ['Winston Churchill', 'Serena Williams'],
    path: 'M 380,480 C 410,500 480,550 460,700 C 450,760 410,790 400,810',
    labelX: 435,
    labelY: 720,
  },
  {
    id: 'head-line',
    name: 'Head Line',
    category: 'lines',
    rating: 5,
    meaning: 'Intellect, cognitive style, concentration power, and psychological processing.',
    traits: ['Rationality', 'Analytical Thinking', 'Creative Problem Solving', 'Mental Clarity'],
    positiveIndications: ['Clear, long line: high intellectual capability, strong memory', 'Curving toward Moon mount: creative and imaginative thinker'],
    challengingIndications: ['Double head line: dualistic thinking patterns', 'Short line: practical, direct, action-oriented approach'],
    modernPsychology: 'Refers to cognitive styles, learning methodologies, and executive functioning.',
    compatibleCareers: ['Software Engineering', 'Research', 'Philosophy', 'Creative Writing'],
    relationships: 'Reflects how you communicate, process relationship conflicts, and express mental compatibility.',
    health: 'Correlates to cognitive fatigue, mental burnout, and headaches.',
    famousPeople: ['Albert Einstein', 'Marie Curie'],
    path: 'M 380,485 C 480,490 580,520 700,580',
    labelX: 570,
    labelY: 530,
  },
  {
    id: 'heart-line',
    name: 'Heart Line',
    category: 'lines',
    rating: 5,
    meaning: 'Emotional capacity, romantic tendencies, empathy, and interpersonal style.',
    traits: ['Empathy', 'Sensory Expression', 'Romance', 'Intuitive connection'],
    positiveIndications: ['Ending between index and middle: balanced, emotionally mature approach', 'Clear, well-defined: warmth, compassion, and emotional security'],
    challengingIndications: ['Chained or fragmented: volatile relationships or emotional instability', 'Very short: reserved, difficulty expressing deep feelings'],
    modernPsychology: 'Reveals attachment styles, emotional regulation patterns, and empathy levels.',
    compatibleCareers: ['Psychology', 'Nursing', 'Human Resources', 'Arts and Entertainment'],
    relationships: 'Determines attachment needs (secure, anxious, avoidant) and romantic idealism.',
    health: 'Linked to the cardiovascular system, chest tightness, and emotional stress responses.',
    famousPeople: ['Princess Diana', 'William Shakespeare'],
    path: 'M 760,490 C 650,470 540,430 400,440',
    labelX: 620,
    labelY: 450,
  },
  {
    id: 'fate-line',
    name: 'Fate Line',
    category: 'lines',
    rating: 4,
    meaning: 'Career trajectory, life purpose, external events, and societal impact.',
    traits: ['Ambition', 'Focus', 'Duty', 'Adaptability to destiny'],
    positiveIndications: ['Strong line rising from base to Saturn: clear life purpose from early on', 'Rising from Luna mount: career success assisted by others/public approval'],
    challengingIndications: ['Absent line: self-guided path without a singular, rigid career focus', 'Breaks or shifts: career pivots, changes of direction, or destiny resets'],
    modernPsychology: 'Measures your perceived self-efficacy, alignment with purpose, and structured work ethics.',
    compatibleCareers: ['Entrepreneurship', 'Executive leadership', 'Project Management', 'Public Relations'],
    relationships: 'Balances personal ambitions with shared relationship goals.',
    health: 'Correlates with career-related stress, workaholism, and alignment-based wellbeing.',
    famousPeople: ['Steve Jobs', 'Oprah Winfrey'],
    path: 'M 500,820 C 500,700 510,550 510,420',
    labelX: 512,
    labelY: 650,
  },
  {
    id: 'sun-line',
    name: 'Sun (Apollo) Line',
    category: 'lines',
    rating: 4,
    meaning: 'Creativity, fame, artistic success, recognition, and wealth potential.',
    traits: ['Charisma', 'Aesthetic Appreciation', 'Magnetism', 'Confidence'],
    positiveIndications: ['Strong, straight line under ring finger: high public recognition, artistic genius', 'Double Sun Line: multifaceted creative talents, multiple income streams'],
    challengingIndications: ['Wavy or broken: obstacles to public recognition or creative blocks', 'Crossed by minor lines: jealousy from others or public misunderstandings'],
    modernPsychology: 'Reflects self-actualisation, creative drive, and need for social validation.',
    compatibleCareers: ['Acting', 'Fine Arts', 'Design', 'Marketing', 'Public Speaking'],
    relationships: 'Influences how charismatic and outgoing one is in romantic endeavors.',
    health: 'Relates to sensory vitality, eyesight, and general radiance.',
    famousPeople: ['Leonardo da Vinci', 'Marilyn Monroe'],
    path: 'M 580,700 C 590,620 600,530 610,430',
    labelX: 610,
    labelY: 520,
  },
  {
    id: 'mercury-line',
    name: 'Mercury Line',
    category: 'lines',
    rating: 3,
    meaning: 'Communication, business acumen, healing abilities, and physical health.',
    traits: ['Eloquence', 'Intuition', 'Persuasiveness', 'Strategic Thinking'],
    positiveIndications: ['Clear, uncrossed line: exceptional mercantile skill, scientific capability', 'Connected to fate line: wealth generated through business intellect'],
    challengingIndications: ['Broken or wavy: liver/digestive issues, business instability', 'Forked at the top: split interests or deceitful tendencies when stressed'],
    modernPsychology: 'Corresponds to logical communication, entrepreneurial spirit, and nervous coordination.',
    compatibleCareers: ['Sales', 'Negotiation', 'Scientific Research', 'Holistic Healing'],
    relationships: 'Determines the level of cognitive alignment and playfulness in partnerships.',
    health: 'Relates to gallbladder, digestive system, and nervous communication.',
    famousPeople: ['Benjamin Franklin', 'Nikola Tesla'],
    path: 'M 620,780 C 640,690 680,570 720,470',
    labelX: 680,
    labelY: 610,
  },
  {
    id: 'marriage-lines',
    name: 'Marriage Lines',
    category: 'lines',
    rating: 3,
    meaning: 'Affections, significant relationships, marriage, and emotional attachments.',
    traits: ['Commitment', 'Sensuality', 'Devotion', 'Intimacy'],
    positiveIndications: ['Straight, clear horizontal lines: deep, fulfilling lifelong commitments', 'Curving slightly upward: prosperous and harmonious marriage'],
    challengingIndications: ['Curving downward: partner outliving or disillusionment in love', 'Forked at the end: separation or emotional distance in relationship'],
    modernPsychology: 'Reflects expectations of intimacy, commitment capacity, and relationship patterns.',
    compatibleCareers: ['Relationship Counseling', 'Family Law', 'Social Work'],
    relationships: 'Indicates the timing and intensity of deep romantic attachments.',
    health: 'Correlated with stress relating to domestic partnership stability.',
    famousPeople: ['Elizabeth Taylor', 'Richard Burton'],
    path: 'M 750,470 Q 765,468 780,465 M 748,460 Q 763,458 778,455',
    labelX: 785,
    labelY: 460,
  },
  {
    id: 'bracelet-lines',
    name: 'Bracelet Lines',
    category: 'lines',
    rating: 3,
    meaning: 'Longevity, health, wealth, and spiritual alignment.',
    traits: ['Robustness', 'Foundation', 'Ancestral strength', 'Inner peace'],
    positiveIndications: ['Three clear, unbroken lines: the "royal bracelets" indicating long life and prosperity', 'First line curved upward: creative spiritual orientation'],
    challengingIndications: ['Broken first line: issues with vitality in early life', 'Chained bracelets: financial fluctuations or physical strain'],
    modernPsychology: 'Symbolises somatic foundations, unconscious security, and generational inheritance.',
    compatibleCareers: ['Yoga instruction', 'Geriatrics', 'Wealth Advisory'],
    relationships: 'Represents the hereditary basis of wellness and familial grounding.',
    health: 'Relates to reproductive health (especially the first line) and general spine/physical alignment.',
    famousPeople: ['Mahatma Gandhi'],
    path: 'M 420,840 C 470,855 530,855 580,840 M 410,855 C 465,875 535,875 590,855 M 400,870 C 460,895 540,895 600,870',
    labelX: 500,
    labelY: 865,
  },

  // --- MOUNTS ---
  {
    id: 'mount-jupiter',
    name: 'Mount of Jupiter',
    category: 'mounts',
    planet: 'Jupiter',
    planetSymbol: '♃',
    constellationPoints: [[335, 430], [365, 460], [355, 420], [350, 445]],
    rating: 5,
    meaning: 'Ambition, leadership, authority, spirituality, and self-confidence.',
    traits: ['Generosity', 'Leadership', 'Pride', 'High Ideals'],
    positiveIndications: ['Well-developed: natural leader, optimistic, generous, highly ambitious', 'Star on mount: highly successful public career or marriage'],
    challengingIndications: ['Flat/depressed: lack of self-esteem, passive nature', 'Overdeveloped: bossy, arrogant, power-hungry'],
    modernPsychology: 'Measures self-worth, social influence, and executive presence.',
    compatibleCareers: ['Politics', 'Education', 'Corporate Leadership', 'Ministry'],
    relationships: 'Generous and protective partner, seeks intellectual equals.',
    health: 'Relates to metabolism, liver functions, and blood pressure.',
    famousPeople: ['Barack Obama'],
    path: 'M 300,445 C 300,400 410,400 410,445 C 410,490 300,490 300,445 Z',
    labelX: 355,
    labelY: 440,
  },
  {
    id: 'mount-saturn',
    name: 'Mount of Saturn',
    category: 'mounts',
    planet: 'Saturn',
    planetSymbol: '♄',
    constellationPoints: [[450, 415], [480, 445], [490, 420], [465, 435]],
    rating: 4,
    meaning: 'Duty, responsibility, discipline, philosophy, and solitude.',
    traits: ['Prudence', 'Introspection', 'Patience', 'Structure'],
    positiveIndications: ['Modestly developed: wisdom, analytical mind, reliable, law-abiding', 'Single vertical line: quiet success and financial security later in life'],
    challengingIndications: ['Overdeveloped: melancholy, cynical, overly introverted', 'Flat: lighthearted but potentially irresponsible or lacking depth'],
    modernPsychology: 'Associated with mental resilience, boundaries, and super-ego/conscientiousness.',
    compatibleCareers: ['Engineering', 'Mathematics', 'Philosophy', 'Agriculture'],
    relationships: 'Serious and committed; may take time to open up emotionally.',
    health: 'Relates to bones, teeth, joints, and auditory health.',
    famousPeople: ['Abraham Lincoln'],
    path: 'M 420,435 C 420,390 530,390 530,435 C 530,480 420,480 420,435 Z',
    labelX: 475,
    labelY: 430,
  },
  {
    id: 'mount-apollo',
    name: 'Mount of Apollo (Sun)',
    category: 'mounts',
    planet: 'Apollo (Sun)',
    planetSymbol: '☉',
    constellationPoints: [[565, 415], [605, 445], [585, 435], [595, 420]],
    rating: 5,
    meaning: 'Artistic talent, aesthetic taste, success, beauty, and wealth.',
    traits: ['Creativity', 'Charisma', 'Joy', 'Expressiveness'],
    positiveIndications: ['Well-developed: love for art, highly expressive, magnetically charming', 'Sun-ray lines: multiple creative accomplishments and fame'],
    challengingIndications: ['Flat: lack of appreciation for beauty, monotonous life', 'Overdeveloped: boastful, vanity-driven, seeking spotlight at all costs'],
    modernPsychology: 'Expresses need for validation, aesthetic drives, and ego integration.',
    compatibleCareers: ['Design', 'Performing Arts', 'Advertising', 'Fashion'],
    relationships: 'Warm, passionate, and expressive; loves grand romantic gestures.',
    health: 'Relates to eyes, heart, and general circulation.',
    famousPeople: ['Walt Disney'],
    path: 'M 540,440 C 540,395 650,395 650,440 C 650,485 540,485 540,440 Z',
    labelX: 595,
    labelY: 435,
  },
  {
    id: 'mount-mercury',
    name: 'Mount of Mercury',
    category: 'mounts',
    planet: 'Mercury',
    planetSymbol: '☿',
    rating: 4,
    meaning: 'Communication, commerce, intelligence, quick wit, and adaptability.',
    traits: ['Eloquence', 'Business Acumen', 'Intellect', 'Inventiveness'],
    positiveIndications: ['Well-developed and firm: excellent communication, commercial success, sharp wit', 'Clear vertical lines: natural healing capacity or counseling skill'],
    challengingIndications: ['Flat: difficulty expressing thoughts, struggles in negotiation', 'Overdeveloped & twisted: manipulative speech, restless mindset'],
    modernPsychology: 'Governs verbal intelligence, executive negotiation, and cognitive agility.',
    compatibleCareers: ['Entrepreneurship', 'Journalism', 'Law', 'Tech & Sales'],
    relationships: 'Communicative, playful, intellectually engaging; values mental stimulation.',
    health: 'Relates to nervous system, lungs, and speech articulation.',
    famousPeople: ['Steve Jobs', 'Benjamin Franklin'],
    path: 'M 660,480 C 660,440 755,440 755,480 C 755,520 660,520 660,480 Z',
    labelX: 715,
    labelY: 475,
  },
  {
    id: 'mount-venus',
    name: 'Mount of Venus',
    category: 'mounts',
    planet: 'Venus',
    planetSymbol: '♀',
    constellationPoints: [[280, 680], [330, 720], [310, 690], [350, 710]],
    rating: 5,
    meaning: 'Love, passion, vitality, physical beauty, and sexual energy.',
    traits: ['Warmth', 'Sensuality', 'Empathy', 'Artistic appreciation'],
    positiveIndications: ['Broad, firm, and high: high physical stamina, warm heart, loving parent/partner', 'Fine grille pattern: highly romantic and refined sensual nature'],
    challengingIndications: ['Flat and pale: low vitality, cold nature, difficulties in intimacy', 'Overdeveloped & hard: aggressive passions, demanding temperament'],
    modernPsychology: 'Represents emotional warmth, core vitality, and attachment intimacy.',
    compatibleCareers: ['Catering & Culinary', 'Childcare', 'Artistic fields', 'Therapy'],
    relationships: 'Passionate, affectionate, and deeply sensual; values touch and physical presence.',
    health: 'Relates to reproductive system, endocrine glands, and base physical stamina.',
    famousPeople: ['Audrey Hepburn'],
    path: 'M 380,480 C 420,530 460,650 420,770 C 370,810 320,800 270,720 C 240,650 280,540 380,480 Z',
    labelX: 340,
    labelY: 650,
  },
  {
    id: 'mount-luna',
    name: 'Mount of Luna (Moon)',
    category: 'mounts',
    planet: 'Luna (Moon)',
    planetSymbol: '☽',
    constellationPoints: [[680, 720], [630, 750], [660, 780], [650, 740]],
    rating: 5,
    meaning: 'Imagination, intuition, subconscious mind, travel, and mystery.',
    traits: ['Intuition', 'Creative vision', 'Daydreamer', 'Empathy'],
    positiveIndications: ['Well-developed: strong intuition, rich dreams, psychic abilities, love for travel', 'Travel lines entering: frequent change of scenery, global lifestyle'],
    challengingIndications: ['Overdeveloped: overactive imagination, anxiety, prone to illusions/escapism', 'Flat: practical but dry, lacks creative vision, strictly logical'],
    modernPsychology: 'Relates to the intuitive right-brain processing, dream states, and depth psychology.',
    compatibleCareers: ['Novel writing', 'Astrology/Tarot', 'Oceanography', 'Visual Art'],
    relationships: 'Dreamy and empathetic partner; seeks a soulful connection.',
    health: 'Relates to body fluids, kidneys, and psychosomatic health.',
    famousPeople: ['J.K. Rowling'],
    path: 'M 750,570 C 760,660 740,780 620,810 C 600,800 580,720 620,620 C 640,570 700,560 750,570 Z',
    labelX: 680,
    labelY: 710,
  },
  {
    id: 'upper-mars',
    name: 'Upper Mars',
    category: 'mounts',
    planet: 'Mars (Passive)',
    planetSymbol: '♂',
    constellationPoints: [[700, 520], [740, 530], [720, 550]],
    rating: 4,
    meaning: 'Moral courage, mental resilience, self-control, and endurance.',
    traits: ['Patience', 'Resilience', 'Moral integrity', 'Defensive strength'],
    positiveIndications: ['Firm and thick: exceptional mental endurance under crisis, calm nature', 'Unblemished: peaceful strength, stands up for injustice quietly'],
    challengingIndications: ['Flat: easily discouraged, yields to pressure', 'Overdeveloped: stubbornness, unable to back down even when wrong'],
    modernPsychology: 'Measures psychological grit, frustration tolerance, and assertiveness boundaries.',
    compatibleCareers: ['Crisis Management', 'Military Strategy', 'Psychotherapy', 'Defense Law'],
    relationships: 'Loyal and steady, acts as a protective shield in family life.',
    health: 'Relates to immune system resilience and blood purification.',
    famousPeople: ['Nelson Mandela'],
    path: 'M 690,500 C 740,500 760,540 730,580 C 680,570 670,530 690,500 Z',
    labelX: 720,
    labelY: 530,
  },
  {
    id: 'lower-mars',
    name: 'Lower Mars',
    category: 'mounts',
    planet: 'Mars (Active)',
    planetSymbol: '♂',
    constellationPoints: [[330, 500], [370, 530], [350, 550]],
    rating: 4,
    meaning: 'Physical courage, aggression, initiative, and combativeness.',
    traits: ['Bravery', 'Impulsiveness', 'Decisiveness', 'Action-oriented'],
    positiveIndications: ['Well-developed: fearless, loves challenges, high competitive drive', 'A star on lower mars: military honors or heroic actions under pressure'],
    challengingIndications: ['Flat: avoids conflict to a fault, timid, lacks initiative', 'Overdeveloped: hot-tempered, aggressive, prone to physical altercations'],
    modernPsychology: 'Relates to fight-or-flight triggers, ambition drive, and competitive spirit.',
    compatibleCareers: ['Sports', 'Firefighting', 'Emergency Services', 'Corporate Turnaround'],
    relationships: 'Passionate and chasing, loves the excitement of conquest.',
    health: 'Relates to red blood cells, muscle tone, and adrenal response.',
    famousPeople: ['Bruce Lee'],
    path: 'M 370,480 C 400,510 390,550 350,560 C 310,540 320,490 370,480 Z',
    labelX: 350,
    labelY: 520,
  },
  {
    id: 'plain-mars',
    name: 'Plain of Mars',
    category: 'mounts',
    planet: 'Mars (Neutral)',
    planetSymbol: '♂',
    rating: 4,
    meaning: 'Temperament, emotional balance, conflict resolution, and life struggles.',
    traits: ['Fortitude', 'Equanimity', 'Self-awareness', 'Directness'],
    positiveIndications: ['Flat and firm: balanced temper, handles stress with poise', 'A deep hollow: struggle in early years leading to deep self-awareness'],
    challengingIndications: ['Overly deep/flabby: easily influenced by surroundings, emotional chaotic', 'Highly lined/crossed: high internal stress and continuous worries'],
    modernPsychology: 'Reveals the baseline emotional equilibrium, stress integration, and emotional maturity.',
    compatibleCareers: ['Diplomacy', 'Mediation', 'Project Coordination'],
    relationships: 'Values peace and open, direct communication; hates passive-aggressive behaviors.',
    health: 'Relates to digestive stomach alignment, stress digestion, and cortisol levels.',
    famousPeople: ['Dalai Lama'],
    path: 'M 420,480 C 550,475 660,500 680,580 C 600,640 450,700 410,640 C 390,560 400,500 420,480 Z',
    labelX: 520,
    labelY: 580,
  },

  // --- FINGERS ---
  {
    id: 'finger-thumb',
    name: 'Thumb (Will & Logic)',
    category: 'fingers',
    planet: 'Venus (Base)',
    planetSymbol: '👍',
    rating: 5,
    meaning: 'Willpower, logic, drive, and personal character strength.',
    traits: ['Determination', 'Reasoning', 'Independence', 'Assertiveness'],
    positiveIndications: ['Long, sturdy thumb: strong will, leadership potential, balanced logic', 'Flexible tip: generous, open-minded, adaptable to change'],
    challengingIndications: ['Very short thumb: easily influenced by others, lacks perseverance', 'Stiff thumb: stubborn, highly resistant to new ideas'],
    modernPsychology: 'Measures ego strength, executive control, and determination to succeed.',
    compatibleCareers: ['Law', 'Management', 'Politics', 'Inventing'],
    relationships: 'Stands firm in commitments; loyal but requires space.',
    health: 'Relates to the brain stem, spinal alignment, and coordination.',
    famousPeople: ['Napoleon Bonaparte'],
    path: 'M 330,620 C 220,580 140,540 180,480 C 230,420 300,500 360,560 Z',
    labelX: 200,
    labelY: 500,
  },
  {
    id: 'finger-index',
    name: 'Index Finger (Jupiter)',
    category: 'fingers',
    planet: 'Jupiter',
    planetSymbol: '☝️',
    rating: 5,
    meaning: 'Ego, ambition, leadership, power, and authority.',
    traits: ['Assertiveness', 'Command', 'Ambition', 'Philosophy'],
    positiveIndications: ['Longer than ring finger: natural leader, high self-confidence, goal-oriented', 'Straight and strong: highly ethical leadership and fair play'],
    challengingIndications: ['Shorter than ring finger: cautious, avoids spotlight, lower self-concept', 'Crooked index: unconventional moral standards or ego conflicts'],
    modernPsychology: 'Reflects self-actualisation, social power motivations, and directive drive.',
    compatibleCareers: ['Teaching', 'Executive Management', 'Public Relations'],
    relationships: 'Dominant or protective; takes charge of scheduling and direction.',
    health: 'Linked to thyroid, larynx, and vocal cord stamina.',
    famousPeople: ['Julius Caesar'],
    path: 'M 320,400 C 300,300 280,180 320,140 C 360,110 380,240 390,390 Z',
    labelX: 320,
    labelY: 200,
  },
  {
    id: 'finger-middle',
    name: 'Middle Finger (Saturn)',
    category: 'fingers',
    planet: 'Saturn',
    planetSymbol: '🖕',
    rating: 5,
    meaning: 'Balance, responsibility, law, fate, and introspective research.',
    traits: ['Prudence', 'Integrity', 'Discipline', 'Serious mind'],
    positiveIndications: ['Long and straight: highly responsible, analytical, values order and safety', 'Thick and sturdy: reliable anchor in crisis, realistic outlook'],
    challengingIndications: ['Crooked middle: eccentric views on laws or prone to self-blaming', 'Extremely long: prone to isolation, loneliness, and severe cynicism'],
    modernPsychology: 'Measures super-ego, self-discipline, and structure processing.',
    compatibleCareers: ['Scientific Research', 'Architecture', 'Judicial Systems', 'Banking'],
    relationships: 'The "responsible adult" in relationships; stable but needs emotional warming.',
    health: 'Relates to bone structures, knees, and nervous system insulation.',
    famousPeople: ['Isaac Newton'],
    path: 'M 430,380 C 430,260 440,100 480,70 C 520,70 520,230 510,380 Z',
    labelX: 470,
    labelY: 130,
  },
  {
    id: 'finger-ring',
    name: 'Ring Finger (Apollo)',
    category: 'fingers',
    planet: 'Apollo (Sun)',
    planetSymbol: '🎨',
    rating: 5,
    meaning: 'Creativity, expression, risk-taking, appreciation of beauty.',
    traits: ['Aesthetics', 'Charisma', 'Risk appetite', 'Joyous nature'],
    positiveIndications: ['Longer than index: highly creative, calculated risk-taker, loves elegance', 'Straight & graceful: natural artistic execution and charisma'],
    challengingIndications: ['Crooked ring finger: creative blockages or emotional suppression', 'Extremely long: gambler personality, impulsive risk-taking'],
    modernPsychology: 'Reflects right-brain orientation, creative expression needs, and risk tolerance.',
    compatibleCareers: ['Arts', 'Investment Banking', 'Entertainment', 'Creative Direction'],
    relationships: 'Playful, exciting, romantic; values beauty, art, and date nights.',
    health: 'Relates to sensory organs, eyes, and skin vitality.',
    famousPeople: ['Wolfgang Amadeus Mozart'],
    path: 'M 550,380 C 560,260 570,120 610,90 C 650,90 640,240 620,380 Z',
    labelX: 610,
    labelY: 140,
  },
  {
    id: 'finger-pinky',
    name: 'Pinky Finger (Mercury)',
    category: 'fingers',
    planet: 'Mercury',
    planetSymbol: '💬',
    rating: 4,
    meaning: 'Communication, business logic, scientific intellect, and relations.',
    traits: ['Eloquence', 'Tact', 'Witty', 'Networking'],
    positiveIndications: ['Reaches the top joint of ring finger: excellent verbal and written communication', 'Long pinky: natural networker, high business acumen'],
    challengingIndications: ['Short pinky: shyness, difficulties expressing inner feelings verbally', 'Low-set pinky: obstacles in early career, self-made success story'],
    modernPsychology: 'Reveals communication capacity, business instinct, and social adaptiveness.',
    compatibleCareers: ['Journalism', 'Trading', 'Publicity', 'Mediator'],
    relationships: 'Flirtatious, witty communicator, loves intellectual bantering.',
    health: 'Linked to ears, speech centers, and coordination.',
    famousPeople: ['Oscar Wilde'],
    path: 'M 670,420 C 690,320 730,220 760,200 C 790,200 760,320 730,420 Z',
    labelX: 750,
    labelY: 260,
  },

  // --- SPECIAL MARKINGS ---
  {
    id: 'marking-mystic-cross',
    name: 'Mystic Cross',
    category: 'markings',
    rating: 5,
    meaning: 'Intuition, interest in the occult, psychic abilities, and spiritual protection.',
    traits: ['Sixth sense', 'Mystical affinity', 'Insightful', 'Claircognizance'],
    positiveIndications: ['Clear X between Heart and Head lines: powerful intuitive insights, protected life path', 'Centered: balanced connection between heart (emotion) and head (logic)'],
    challengingIndications: ['Faint or broken: undeveloped intuitive abilities or spiritual doubt'],
    modernPsychology: 'Represents deep integration of emotional intelligence and cognitive pattern-recognition.',
    compatibleCareers: ['Psychology', 'Astrology', 'Philosophy', 'Holistic Healing'],
    relationships: 'Intuitively senses partner needs; deep, soulful bonds.',
    health: 'Linked to pineal gland activation and parasympathetic nervous system.',
    famousPeople: ['Edgar Cayce'],
    path: 'M 530,480 L 560,520 M 560,480 L 530,520',
    labelX: 545,
    labelY: 500,
  },
  {
    id: 'marking-girdle-venus',
    name: 'Girdle of Venus',
    category: 'markings',
    rating: 4,
    meaning: 'Sensory sensitivity, deep empathy, emotional depth, and artistic temperament.',
    traits: ['Super-empathy', 'Aesthetic sensitivity', 'Intensity', 'Passion'],
    positiveIndications: ['Fine arc above heart line: refined sense of beauty, deep empathic capacity', 'Fragmented arc: highly responsive artistic spirit, feels things deeply'],
    challengingIndications: ['Deep, heavy girdle: over-sensitivity, easily overwhelmed by others\' emotions'],
    modernPsychology: 'Indicates high sensory processing sensitivity (HSP) and aesthetic responsiveness.',
    compatibleCareers: ['Fine Arts', 'Music', 'Poetry', 'Sensory Branding'],
    relationships: 'Extremely passionate and emotionally intense; seeks total union.',
    health: 'Relates to high nervous susceptibility and skin sensitivities.',
    famousPeople: ['Vincent van Gogh'],
    path: 'M 450,420 C 530,390 610,390 680,410',
    labelX: 565,
    labelY: 395,
  },
  {
    id: 'marking-ring-solomon',
    name: 'Ring of Solomon',
    category: 'markings',
    rating: 4,
    meaning: 'Wisdom, spiritual understanding, teaching capacity, and psychic shielding.',
    traits: ['Wisdom', 'Psychic insight', 'Pedagogical skill', 'Regal presence'],
    positiveIndications: ['Curved line wrapping Jupiter mount: natural teacher, advisor, deep spiritual wisdom'],
    challengingIndications: ['Double ring: extreme focus on occult mysteries to the neglect of practical life'],
    modernPsychology: 'Measures mentor abilities, archetypal wisdom, and high emotional safety signals.',
    compatibleCareers: ['Teaching', 'Advising', 'Spiritual leadership', 'Consulting'],
    relationships: 'Provides calm, wise counsel; steady anchor in family crisis.',
    health: 'Linked to crown chakra alignment and mental serenity.',
    famousPeople: ['King Solomon', 'Socrates'],
    path: 'M 320,425 C 330,405 385,405 395,425',
    labelX: 360,
    labelY: 410,
  },
  {
    id: 'marking-ring-saturn',
    name: 'Ring of Saturn',
    category: 'markings',
    rating: 3,
    meaning: 'Skepticism, strict boundaries, obstacles, and intense self-reflection.',
    traits: ['Self-criticism', 'Stoicism', 'Vigilance', 'Independence'],
    positiveIndications: ['Present: serves as a filter that blocks superficial interactions, forcing depth'],
    challengingIndications: ['Severe ring: feeling blocked, self-sabotaging career behaviors, isolation'],
    modernPsychology: 'Relates to hyper-vigilance, early-life boundary issues, and defensive self-criticism.',
    compatibleCareers: ['Compliance Auditing', 'Risk Assessment', 'Research Coding'],
    relationships: 'Extremely selective in partner choice; requires absolute safety before opening.',
    health: 'Relates to joint rigidity, chronic stress storage, and dental alignments.',
    famousPeople: ['Friedrich Nietzsche'],
    path: 'M 440,415 C 450,395 510,395 520,415',
    labelX: 480,
    labelY: 405,
  }
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: 'Which major line represents vital energy, core physical health, and major life path changes?',
    options: ['Heart Line', 'Head Line', 'Life Line', 'Fate Line'],
    correctIndex: 2,
    explanation: 'The Life Line curves around the thumb base (Mount of Venus) and represents core physical vitality, health, and major transitions in one\'s life path.'
  },
  {
    id: 2,
    question: 'Which planetary mount, located directly under the index finger, signifies ambition, leadership, and confidence?',
    options: ['Mount of Saturn', 'Mount of Jupiter', 'Mount of Apollo', 'Mount of Mercury'],
    correctIndex: 1,
    explanation: 'The Mount of Jupiter sits below the index finger and represents your capacity for leadership, social influence, ambition, and self-confidence.'
  },
  {
    id: 3,
    question: 'What does the Mystic Cross, located between the Heart Line and the Head Line, traditionally indicate?',
    options: ['A major illness in mid-life', 'Exceptional financial luck', 'Intuition, psychic abilities, and interest in the occult', 'A career change or move abroad'],
    correctIndex: 2,
    explanation: 'The Mystic Cross (often an X shape in the center of the palm) represents high intuition, deep connection to mysticism, and a protective spiritual energy.'
  },
  {
    id: 4,
    question: 'Which finger is associated with the planet Saturn, representing duty, discipline, law, and responsible structure?',
    options: ['Index Finger', 'Middle Finger', 'Ring Finger', 'Pinky Finger'],
    correctIndex: 1,
    explanation: 'The Middle Finger represents Saturn, which stands for introspection, wisdom, responsibility, boundaries, and life structures.'
  },
  {
    id: 5,
    question: 'A Head Line that curves deeply downward toward the Mount of Luna (Moon) signifies what kind of cognitive style?',
    options: ['Analytical and strictly logical', 'Highly creative, imaginative, and intuitive', 'Scattered and unfocused', 'Aggressive and confrontational'],
    correctIndex: 1,
    explanation: 'The Mount of Luna represents imagination and the subconscious. A Head Line dipping into it shows a highly creative, artistic, and imaginative cognitive process.'
  }
];

export const achievementsList: Achievement[] = [
  {
    id: 'scholar',
    title: 'Palmistry Scholar',
    description: 'Explore all 8 palm lines and study their spiritual pathways.',
    icon: '📜'
  },
  {
    id: 'mystic',
    title: 'Planetary Mystic',
    description: 'Explore all 9 planetary mounts on the palm.',
    icon: '🪐'
  },
  {
    id: 'quizmaster',
    title: 'Grand Master Palmist',
    description: 'Complete the Palmistry Quiz with a 100% perfect score.',
    icon: '🏆'
  }
];
